spring:
  application:
    name: user-manager
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/user_management

server:
  port: 8080

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false